default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: Messages
  password: messages

development:
  <<: *default
  database: messages_development

test:
  <<: *default
  database: messages_test

production:
  <<: *default
  database: messages_production
